### ISSUE TITLE
Jellyfin server behind traefik with custom certificate authority

### ISSUE THREAD

**Issue by Kiblyn11** [jellyfin/jellyfin-tizen#167]
Hello,

I am trying to use Jellyfin app for Tizen.
I cannot add my server when on the app, generic error message.
I serve Jellyfin through Traefik with a certificate signed by a custom CA (mkcert).
I suspect that I Jellyfin has an issue because it does not trust SSL certificate.

Is there any option to skip SSL verification on the app or to add custom CA to Tizen TV (It seems not when skimming through menus) ?

**Comment by dmitrylyzo** [comment]
Similar issues, but due to expired Let's Encrypt root certificate:
#119
#161

> Is there any option to skip SSL verification on the app

By using HTTP. :man_shrugging: 

>  to add custom CA to Tizen TV (It seems not when skimming through menus) ?

I don't know how to add a trusted certificate to the TV (https://github.com/jellyfin/jellyfin-tizen/issues/119#issuecomment-1117458322).

I haven't tried, but https://github.com/Samsung/tizen-docs/blob/master/docs/application/tizen-studio/common-tools/command-line-interface.md#using-your-own-certificates

**Comment by Kiblyn11** [comment]
Thanks for bringing solutions.
I will try to package my root CA with the application.
