### ISSUE TITLE
[Question] Autobuild and update

### ISSUE THREAD

**Issue by jasimancas** [jellyfin/jellyfin-tizen#45]
Hi, I have a question, is it possible to auto-generate a WGT automatically in order to have the TV version updated until the release in the app store?

When do I need to upgrade? When there are changes in this repo or when there are changes in the repo-web?

**Comment by dmitrylyzo** [comment]
> Hi, I have a question, is it possible to auto-generate a WGT automatically in order to have the TV version updated until the release in the app store?

There is PR #17 which introduces auto-build (#13), but you will still need to sign WGT with your certificate and install from Tizen Studio/CLI.
There is a chance that we may be able to release test builds for installation via USB. I haven't tested this, but it will probably only be stable releases because it cannot be done automatically.

> When do I need to upgrade?

Ideally, `jellyfin-web` should have the same version as on the server, but in most cases, (not outdated) `master` will work with the latest stable release. FYI, you can build WGT not only with `master` branch but also with stable one.

> When there are changes in this repo or when there are changes in the repo-web?

Both. Tizen repo is rarely updated because it is just a wrapper and requires minor changes.

**Comment by jasimancas** [comment]
Ok thanks, in that case the ideal would be to update at the same time that I update the server so that both are in the same version.

Is there a date scheduled to appear in the store? once the store application appears it will update at the same time as the server automatically as for example Netflix does not?

**Comment by dmitrylyzo** [comment]
> Is there a date scheduled to appear in the store?

We don't have any ETA. Besides, I think we aren't completely comply Samsung requirements (at first glance, some minor mistakes).

> once the store application appears it will update at the same time as the server automatically as for example Netflix?

It depends on how quickly Samsung accepts new version, but I think when we get there app will update at the same time.
