### ISSUE TITLE
Is yarn still used?

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-tizen#77]
Followed the documentation for Linux on a fresh Ubuntu VM. First attempt at building errors and tells me yarn is incompatible. I'm on the latest version of yarn (1.22.10).

**Comment by dmitrylyzo** [comment]
This has been changed in `jellyfin-web`:
- for stable 10.7.x and older: `yarn install`
- for master branch: `npm ci`

btw, for `jellyfin-tizen` you can use `npm i` with the same environment variable `JELLYFIN_WEB_DIR`.
_`i` because I still don't use lockfiles_

**Comment by MeltedEnvy** [comment]
Worked well, thank you. I can't seem to add Tizen studio to path, adding it to .bashrc did nothing. Is there a guide on how to build the wgt using the GUI?

**Comment by dmitrylyzo** [comment]
Try this in `.bashrc` (correct the path to the root of Tizen Studio if necessary)
```sh
# Add the directory of Tizen .NET Command Line Tools to user path.
export PATH=$HOME/tizen-studio/tools/ide/bin:$PATH
```

> Is there a guide on how to build the wgt using the GUI?

There is no guide. From CLI is easier.
Looks like I can't import it as `Tizen/Tizen Project` because I didn't push studio files (`.project`, `.tproject`).
As an option, create new TV project and replace its content.
`New -> Tizen Project -> Template -> TV (TV v5.0 or TV-samsung v6.0) -> Web Application -> Basic UI`.
You need to uncheck some folders/files for a proper build: https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-633616422
But again, from CLI is easier, unless you want to debug it.

**Comment by MeltedEnvy** [comment]
Yeah the tizen-studio is in my home folder and I have it added like that to .bashrc but it's still not being picked up. Took a look at the GUI and I think I'll hold off until there's a simpler installation method because I'm a bit sick of troubleshooting this. Thanks a lot for the help though.
