### ISSUE TITLE
when playing movies it freezes for 5 seconds

### ISSUE THREAD

**Issue by elvis0288** [jellyfin/jellyfin-tizen#9]
Hello my friend thank you for your work i really appreciate it. when playing tv shows they work flawlessly and without any issue but when i play any movie on any format, it will freeze for 5 to 10 seconds every minute or 2 or movie. when playing same movie in my jellyfin web client on pc or android phone it is working correctly. i thought it could be the transcoding but this is happening with direct play also

**Comment by dmitrylyzo** [comment]
That's strange since (_I believe_) videoplayer pipeline is the same.

What TV model?
What Jellyfin server version?
What version of `jellyfin-web` did you use for WGT?
Is there difference between formats of tv shows and freezing movie?
Are there any errors in the server log when it freezes?

Since app is just web-wrapper, please try to run the same (freezing) movie from Tizen browser.
In this case you will use `jellyfin-web` from server.

**Comment by elvis0288** [comment]
after a lot of testing, it looks like the problem is when using a 4k movie... if i download the same movie in 1080p it works fine but if i download the movie in 4k even if it says direct play, it will freeze

**Comment by dmitrylyzo** [comment]
Can you post mediainfo log for 4K video that freezes?

**Comment by elvis0288** [comment]
Hello dmitry so after doing more testing, it looks like i was dumb enough to add my reverse dns ip into my local tv instead of using the local ip so i guess the cloudfare was not ok with me trying to stream 4k movies or even 2k movies.. i used the local ip and now it is working perfectly.

sorry and thank you for your job

**Comment by yarons** [comment]
It can't be fixed as part of Jellyfin, this issue can be closed.
