### ISSUE TITLE
Screen Goes Blank On Scroll After Exiting App 

### ISSUE THREAD

**Issue by wbry21** [jellyfin/jellyfin-tizen#98]
Hey

Forgive me I'm new to TV development. I'm encountering an issue where on first install it worked perfectly after exiting the app you're able to see the full screen up until you start scrolling once you scroll the screen comes up blank if I uninstall the application and reinstall it works. Any insight on how I can debug this issue?

![image](https://user-images.githubusercontent.com/61174427/147169458-302c882e-6872-4534-994a-33ad8cf3f53d.png)
![image](https://user-images.githubusercontent.com/61174427/147169477-acb46a3a-7b28-4158-b2fc-47b48d39817f.png)

TV Model: QN65Q70AAFXZA
Software Version: T-NKM2AKUC-1805.4

Steps to reproduce: 

Login to Jellyfin
Press the back button until you are asked Do you want to exit? 
Click Yes 

The next time I open the app I have this issue 

Thank You in advance

**Comment by dmitrylyzo** [comment]
It seems that you are using a custom CSS theme where scrolling is set incorrectly: the page div (`data-role="page"`) has `overflow: visible` (instead of `overflow: auto` or `overflow: scroll`) - so it is not considered (by ScrollManager) as a scroller.

You can disable custom CSS using the `Disable Server-Provided Custom CSS` option in the `Display` settings section. But you need to temporarily comment out `@import` in the Dashboard (from PC) as the `Save` button is also inaccessible.

**Comment by wbry21** [comment]
Hey Dmitry,

Thank You so much your 100% right.  

Just in case if anyone is using 
https://github.com/prayag17/JellySkin themes you need to add 

.layout-tv div[data-role="page"] {
overflow: auto;
}
